### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by Pinghigh** [sakura6264/unlock_music#1]
如题，在win11 25236上没反应，管理员模式也没反应

**Comment by arcana6264** [comment]
程序在netcore3.1下运行，跑不起来可能需要安装微软的dotnet runtime或者dotnet sdk

**Comment by Pinghigh** [comment]
> 程序在netcore3.1下运行，跑不起来可能需要安装微软的dotnet runtime或者dotnet sdk

安装了.net core3.1的runtime，x64和x86 desktop/runtime都装了，还是没反应（

**Comment by arcana6264** [comment]
看到网上一些其他人反映netcore3.1的程序需要安装SDK才能跑起来。

**Comment by arcana6264** [comment]
或者可以由我这边打包runtime再发布（但是这样做程序体积会上升到300M+）
要不您先试试安装SDK？

**Comment by arcana6264** [comment]
抱歉是我的问题，我在打包时忘记了部分文件而程序从我的nuget缓存中读取了这些文件导致了我的电脑上能够运行然而放到其他电脑上无法运行。Release已经更新了，您可以下载新的release，它应该可以正常运行

**Comment by Pinghigh** [comment]
> 抱歉是我的问题，我在打包时忘记了部分文件而程序从我的nuget缓存中读取了这些文件导致了我的电脑上能够运行然而放到其他电脑上无法运行。Release已经更新了，您可以下载新的release，它应该可以正常运行



> 抱歉是我的问题，我在打包时忘记了部分文件而程序从我的nuget缓存中读取了这些文件导致了我的电脑上能够运行然而放到其他电脑上无法运行。Release已经更新了，您可以下载新的release，它应该可以正常运行

（刚想说加了SDK也无法打开）
非常感谢！现在能正常使用了
